### PR TITLE
Auto-merge receipt items for the same product

### PR DESCRIPTION
**Pull request by mtijink**
This allows tapping a button twice, and still show only one receipt
item, but now with quantity 2.

The Receipt.getReceipt() functions is not needed anymore, because the
Receipt.receipt variable is always 'clean' now.

### CODE REVIEW

**Comment by nickschot** [comment]
We thought of implementing it this way before. I don't remember exactly why we didn't, but it was probably because of the workflow the barkeeper has and "feedback" for the barkeeper.

If this implementation goes through, it would probably be a good idea to add some feedback (like a "flash") on the receipt when an amount changes.

I'll ask around a little what people think about it.

**Comment by DanielVoogsgerd** [comment]
Speaking from experience, this is a solid idea. Having separate item on your receipt is really annoying. We (Arago) therefore already merged it.
The flash could be implemented as a bonus, but I've not noticed any issues without it.

**Comment by mtijink** [comment]
I added a flash to show which receipt item updated.

**Comment by nickschot** [comment]
I've made the flash animate the background of a row for a short while, as (animating) box-shadow on a TR element doesn't work.

**Pull request merged**
